amplitude/Amplitude-Node

- packages/node/src/nodeClient.ts
This lets us use api2.amplitude.com to avoid SSL errors on some machines.
> Allow serverUrl to override hostname for request

- packages/node/jest.config.js
- packages/node/package.json
- packages/node/test/mocks/transport.ts
- packages/node/test/transport.test.ts
- yarn.lock
Adds Jest and Nock as dev dependencies to the Node-SDK, and adds light tests to ensure the transport returns the right statuses
> Start Tests for Transport Layer

- packages/node/src/nodeClient.ts
- packages/node/src/transports/http.ts
- packages/types/src/options.ts
Add a single list of events for events that didn't send successfully the first time around.
Eventually, to be refactored to support multiple lists (to separate per user id)
> Add (single) Retry Buffer event queue for events that didn't successfully send

- packages/node/src/constants.ts
- packages/node/src/nodeClient.ts
- packages/node/src/sdk.ts
- packages/types/src/options.ts
Changing the typing of what the node client takes in as a `Partial<Options>` type and then adding a `DEFAULT_OPTIONS` constant.
> Stricten the Options type, pass in partial options

- packages/node/src/transports/http.ts
- packages/types/src/index.ts
- packages/types/src/response.ts
- packages/types/src/retry.ts
- packages/types/src/status.ts
creates types for the body for the [http v2 api](https://developers.amplitude.com/docs/batch-event-upload-api#payloadtoolargeerror) and some helper functions to surface that from the transport layer.
Adds the 413 (Payload too large) error to the list of statuses that could be returned.
> Allow transport layer to surface information from the http v2 api, type the response bodies

- packages/node/src/constants.ts
- tsconfig.json
This did not have the intended effect - the dist was failing to compile correctly.
> hotfix: fix typescript compilation by reverting resolveJsonModule

- packages/node/src/constants.ts
- packages/node/src/nodeClient.ts
- packages/types/src/client.ts
- packages/types/src/index.ts
- packages/types/src/response.ts
Adds an ResponseListener that takes in the resolve and rejects from a Promise
Which facilitates always returning a response.
Resolves Issue #12
return the SKIPPED_RESPONSE for Status.Skipped and StatusCode=0, which seems more fitting if nothing happens.
> feat(client): Return the Response in both `flush` and `logEvent` #30

- packages/node/src/nodeClient.ts
Currently, a second logEvent does not trigger a flush in the next event loop.
This is because the null check from L87 fails.
> fix: Second logEvent does not schedule a flush

- packages/eslint-config-typescript/package.json
- `lerna publish` won't work unless this version is bumped, I believe this is because it wasn't tracked in the 1.0.4 release. See current state: 
* Does your PR have a breaking change?:  no
> chore: change eslint-config-typescript version for lerna publish

- packages/utils/package.json
`1.0.4` didn't involve `yarn build` so it was never updated. This should fix it
> fix(utils): publish 1.0.5 with correct build

- package.json
Run yarn build (lerna's build) before packing and publishing npm publishing, saving myself the embarrassment of publishing the wrong packages and also makes sure the builds succeed.
> fix(ci): prepare builds before actually publishing

- packages/eslint-config-typescript/index.js
- packages/eslint-config-typescript/package.json
- packages/identity/package.json
- packages/identity/src/identity.ts
- packages/identity/src/identityManager.ts
- packages/node/package.json
- packages/node/src/nodeClient.ts
- packages/node/src/retryHandler.ts
- packages/node/src/transports/http.ts
- packages/node/test/mocks/transport.ts
- packages/node/test/transport.test.ts
- packages/types/package.json
- packages/types/src/event.ts
- packages/types/src/identity.ts
- packages/types/src/response.ts
- packages/types/src/retry.ts
- packages/types/src/status.ts
- packages/typescript/package.json
- packages/utils/package.json
- packages/utils/src/index.ts
- packages/utils/src/logger.ts
- packages/utils/src/misc.ts
- packages/utils/src/response.ts
- packages/utils/src/status.ts
Adheres to the tslint recommended eslint rules
- only a few instances of floating promises where necessary (in setTimouts, and also to start the retry logic)
Move the `fromHttpCode` to `mapHttpCodeToStatus` in utils
> chore(lint): Configure all the workspaces to use eslint configurations

- packages/node/src/constants.ts
- packages/node/src/nodeClient.ts
- packages/node/src/retryHandler.ts
- packages/node/test/mocks/retry.ts
- packages/node/test/retry.test.ts
- packages/types/src/options.ts
- Adds `retryTimeouts` to options
- Deprecates `BASE_RETRY_TIMEOUT` and `maxRetries`
- Adds tests for deprecation
- Adjusts `RetryHandler` logic to handle array rather than number
- Replace bit shifting with [`currentRetryTimeout`](https://github.com/amplitude/Amplitude-Node/compare/improve-sleep-retry#diff-f993d036e43711879797431141303499ab67f15598b27a926ca91c6fbfd1b010R203)
- Exposes `options` property of `RetryHandler` so that it can be read from tests
> feat(node): Add baseRetryTimeout option

- packages/node/src/nodeClient.ts
- Adds warning for users trying to use `@amplitude/node` in a browser
> refactor(node): add non-node env warning

- packages/node/src/constants.ts
- packages/node/src/retryHandler.ts
- packages/node/test/retry.test.ts
Forgot to include this change before merging #48 
- Refactor `options.maxRetries` deprecation warning string to constant
- Update tests to make sure warning is called
> refactor(node): Max retries warning refactor

- packages/identity/package.json
- packages/node/package.json
- packages/types/package.json
- packages/utils/package.json
Removes an unnecessary dependency from the build packages of some packages. 
> fix(dependency): Move `@amplitude/eslint-config-typescript` to dev dependencies

- packages/node/src/constants.ts
- packages/node/src/retryHandler.ts
- packages/node/test/mocks/retry.ts
- packages/node/test/mocks/transport.ts
- packages/node/test/retry.test.ts
- packages/types/src/event.ts
- packages/types/src/index.ts
- packages/types/src/options.ts
This implements the behavior requested in #64 
This PR adds a new option to the Node SDK, `options.minIdLength -> number | null | undefined`.  It also adds the necessary logic to append the `options: { minIdLength: x }` key:value pair to the payload send to the HTTP api.
Adds 2 tests to confirm that the payload being sent is modified correctly based on minIdLength being passed as an option, aswell as confirming that the payload is untouched if minIdLength is null or undefined.
* Does your PR have a breaking change?:  no
> feat(min_id_length): Add support and tests for new SDK option `minIdLength`

- packages/identify/README.md
- packages/identify/src/identify.ts
- packages/identify/tests/identify.spec.ts
Adds `$groupIdentify` events to the identify SDK, allowing the Node SDK to more easily create group identify events.
> feat(identify): identifyGroup groupIdentify API for Identify

- packages/utils/src/validate.ts
- packages/utils/test/validate.test.ts
Adds a check to make sure user and device ID's are the correct type (will fail if numeric)
Helps debug #63 (dataPL ticket tracked internally)
> feat(validation): tougher rules on validate for device/user id

- packages/node/src/nodeClient.ts
- packages/types/src/baseEvent.ts
No longer set platform field on every event. Doing so causes other fields to be nulled out, so this change will stop that from occurring by default (see https://developers.amplitude.com/docs/http-api-v2)
* Does your PR have a breaking change?: *No*
> fix(event): no longer set platform field on every event

- .github/workflows/test.yml
- package.json
- packages/eslint-config-typescript/index.js
- packages/eslint-config-typescript/package.json
- packages/identify/.eslintrc.json
- packages/identity/.eslintrc.json
- packages/identity/test/identity.test.ts
- packages/node/.eslintrc.json
- packages/types/.eslintrc.json
- packages/utils/.eslintrc.json
- packages/utils/src/validateProperties.ts
- packages/utils/test/misc.test.ts
- packages/utils/test/queue.test.ts
- packages/utils/test/validateProperties.test.ts
- yarn.lock
Adds the prettier plugin which stops eslint and prettier from fighting in certain files.
Adds ESLint + Prettier as a breaking step in PR Validation, as well as cleans up a few eslint issues.
Next step is to get Prettier + ESLint working well with Husky (+ whatever the best practice is in Lerna/monorepos)
> ci(lint): add eslint prettier plugin, eslint/prettier CI step

- packages/node/README.md
- packages/node/src/index.ts
- packages/node/src/nodeClient.ts
- packages/node/src/retry/baseRetry.ts
- packages/node/src/retry/defaultRetry.ts
- packages/node/src/retry/offlineRetry.ts
- packages/types/src/index.ts
- packages/types/src/options.ts
- packages/types/src/retry.ts
- packages/types/tsconfig.json
Begins to address issues highlighted by #86 :
- exports `Retry` directly form `@amplitude/node` so that a second dep isn't necessary
- exports `BaseRetryHandler` that makes it easier to set up a default transport, etc.
- exports `DefaultTransport` 
- Exports `RetryClass` -> `Retry` in the `@amplitude/types` module to avoid confusion as this is an **interface** to implement and not a Class in itself. deprecating and still exporting `RetryClass` to avoid breaking changes (for now).
> fix(retry): BaseRetryHandler + Make Retry in general easier to play with

- .github/workflows/test.yml
- packages/eslint-config-typescript/index.js
The eslintrc will take the **working directory** as the top level for the typescript parser, unless specified. 
Also fixes an issue where the unit tests build the packages an unnecessary 3 times, because of the `prepare` script (which IMO we should still keep)
- The first time is during `yarn install --frozen-lockfile`. Since lerna doesn't have great tooling around giving subscripts flags when it runs install, decided to keep this step and add the `--ignore-scripts` flag to make sure it doesn't build
- Second time is during `lerna bootstrap`. Decided to keep this for the symlinking of depedencies and decided it was also easy enough to let this still run `prepare`.
- Third was an unnecessary `yarn build`. Just removed this.
> build: Reduce # of times packages get built, better specify tsconfig

- .github/workflows/test.yml
Changes the macOS-10.14 to macOS-latest, triggered when github noticed we weren't using the latest version
> ci: switch macOS environment to latest

- packages/node/src/retry/defaultRetry.ts
Wrap a line of code into the try/catch loop so that it doesn't cause crashes - begins the process to help #99 
Adds a `Array.isArray` check and also changes a `forEach` to a `for...of` for slightly more robustness and performance
> fix: wrap event pre-processing in try/catch loop to catch potential errors

- packages/node/package.json
- packages/node/src/retry/defaultRetry.ts
- packages/node/test/retry.test.ts
- packages/types/src/response.ts
- packages/types/src/status.ts
- yarn.lock
- Fixes `Status.Unknown` response when there's a client-side system error. Instead, it should now return `Status.SystemError` along with the reported node error
> fix: Fix unknown error message response

- packages/identify/src/identify.ts
- packages/identify/test/identify.spec.ts
- packages/node/src/nodeClient.ts
Allow the identify to take null user and device ID, and give a warning if both are empty
> feat: allow identify to take both null user id and null device id

- README.md
- packages/identify/src/identify.ts
- packages/identify/test/identify.spec.ts
- packages/types/src/event.ts
- packages/types/src/identify.ts
- packages/types/src/index.ts
Group Identify was sending the wrong field - fix that
Also add a linking of READMES at the Top Level
> fix(identify): Send group properties instead of user properties for group identify

- packages/types/src/identify.ts
- Allows boolean values for user props when using typescript
- Closes #116
> feat(Identify): Allow boolean as ValidPropertyType for

- packages/node/src/constants.ts
- packages/node/src/retry/defaultRetry.ts
- packages/node/test/retry.test.ts
- packages/types/src/options.ts
- Adds a new option `onRetry` that allows that gives client access to information about retry attempts
- Is a callback with params (response, retryTimeoutsIndex)
- Adds tests to validate when onRetry should or shouldn't be called
> feat: onRetry lifecycle callback

- packages/node/src/retry/offlineRetry.ts
If my understanding of the idea behind OfflineRetryHandler is right then this PR fixes a bug regarding storing `_eventsToRetry`
Events passed to `_onSendError` where only events from the current batch (flush). But OfflineRetryHandler tries to send events from the current batch concatenated with `_eventsToRetry`. As a result:
- only events from the last batch had a chance to be stored in `_eventsToRetry` and after one attempt to send them again they were gone, no matter what was the result of the request.
- I assume the line `newEventsToRetry = events.filter((_, index) => !invalidEventIndices.has(index));` wasn't working properly as `invalidEventIndices` were computed based on events that were send (`_eventsToRetry.concat(events)`) and not `events`. **Edit** that's my assumption about how …
> fix(retry): Storing _eventsToRetry in OfflineRetryHandler

- packages/utils/src/validateProperties.ts
- packages/utils/test/validateProperties.test.ts
Fixes https://github.com/amplitude/Amplitude-Node/issues/116. There was another [PR](https://github.com/amplitude/Amplitude-Node/pull/124) which added `boolean` as a valid type, but it didn't fix the core problem. This PR does and updates the tests to account for `boolean` as a valid value type.
Here is the original issue that was reported: https://github.com/amplitude/Amplitude-Node/issues/116
* [ x ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Node/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
> fix(Identify): Ensure boolean is allowed as a valid property value

- packages/node/src/nodeClient.ts
Middleware is now run prior to event validation in logEvent(). This allows middleware to enrich invalid events prior to validation.
> fix: middleware is now run prior to event validation

- packages/node/src/retry/defaultRetry.ts
- packages/node/test/retry.test.ts
* Add try catch for `ErrnoException` thrown in `_retryEventsOnce()`. Fixes https://github.com/amplitude/Amplitude-Node/issues/154.
* Fix unit test to include a wait on retry to complete before exiting
> fix: Add try catch around retry sendPayload() to handle errors on retry

- packages/node/src/transports/http.ts
- packages/node/test/http.test.ts
Allow using a custom port in the URI. The code changes add support for extracting the port from the URI and setting it if one is given.
Our use-case: we proxy requests to Amplitude through our own endpoint. So in dev environment, it is helpful to be able to override the port in the URI.
> feat(transport): Allow using a custom port in URI

- packages/node/src/nodeClient.ts
- packages/node/test/nodeClient.test.ts
- packages/types/src/baseEvent.ts
- packages/types/src/ingestionMetadata.ts
- packages/types/src/options.ts
- feat: add ingestion_metadata field
Add this option in the configuration, which can be used in the library wrapper/code generation/dynamic loading cases, for setting the `ingestion_metadata` information.
> feat: add ingestion_metadata field

- .github/workflows/release.yml
- .github/workflows/test.yml
- lerna.json
- package.json
- packages/identify/package.json
- packages/identity/package.json
- packages/node/package.json
- packages/node/src/nodeClient.ts
- packages/node/src/retry/defaultRetry.ts
- packages/types/package.json
- packages/typescript/package.json
- packages/utils/package.json
- packages/utils/test/misc.test.ts
- packages/utils/test/queue.test.ts
- yarn.lock
Remediate critical and high Dependabot vulns
Before: 44 dependabot alerts
After: 0 alerts
Note: `lerna` is updated - need to check `publish` logic.
* Does your PR have a breaking change?:  no
> chore: bump versions to remediate critical and high Dependabot vulns
