.github/workflows/test.yml

Added a basic github workflow for `lerna run build` for building on macOS and linux. We can add tests later

ci: Basic github workflow

---

packages/node/package.json
packages/node/src/constants.ts
packages/node/tsconfig.build.json
packages/node/tsconfig.esm.json
packages/types/package.json
packages/types/tsconfig.build.json
packages/types/tsconfig.esm.json
packages/utils/package.json
packages/utils/tsconfig.build.json
packages/utils/tsconfig.esm.json
tsconfig.json

Change rootdir to be '." explicitly - the main dir of each package and *not* src
Change entry to explicitly point into the src

fix(dist): Resolve issues with resolve JSON module by specifying rootdir and entry

---

.github/pull_request_template.md
.github/workflows/semantic-pr.yml
CONTRIBUTING.md

- Add check for PRs for proper title
- Add PR template
- Add contributing.md

ci: semantic pr check

---

packages/utils/src/misc.ts

- Prep util functions for Prototype.js check/fix in Amplitude-JavaScript
- Add `isBrowserEnv`
- Simplify `isNodeEnv` logic

feat: Cleanup isNodeEnv and add isBrowserEnv

---

packages/utils/jest.config.js
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/misc.ts
packages/utils/test/misc.test.ts
yarn.lock

- Adds `prototypeJsFix` to be used in Amplitude-JavaScript
- Related PR: https://github.com/amplitude/Amplitude-JavaScript/pull/313
- Add `isBrowserEnv` and `prototypeJsFix` to exports

feat(utils): Add prototypeJsFix

---

package.json

- Step 1 of 2 on fixing #49. Adds package to workspace so lerna knows to publish it

fix(eslint-config-typescript): Add eslint-config-typescript to workspace

---

jest.config.js
package.json
packages/identity/jest.config.js
packages/node/jest.config.js
packages/node/src/transports/http.ts
packages/types/jest.config.js
packages/types/package.json
packages/types/src/index.ts
packages/types/src/response.ts
packages/utils/jest.config.js
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/response.ts
packages/utils/test/response.test.ts

- Base Jest Config and some added functions
- Move Type Functions to Utils to keep types directory only types 
- Remove jest config in types since there are no tests
- Tests for collectInvalidIndices

ci(tests): Base Jest Config, Move Type Functions to Utils, added tests

---

packages/identity/package.json
packages/utils/package.json

Adds tslib which is used to help compile (see our tsconfig in `/typescript`)

fix(dependency): Add tslib as a dependency to identity and utils

---

package.json
packages/node/src/nodeClient.ts
packages/node/src/retryHandler.ts
packages/utils/src/index.ts
packages/utils/src/validate.ts
packages/utils/test/misc.test.ts
packages/utils/test/validate.test.ts

- Adds the `isValidEvent` test that makes sure that events have some validity to them:
- A valid event type
- A device OR user id
- Adds tests to check.

feat(validation): Validate events before the Node Client takes action on them.

---

.github/pull_request_template.md
.github/workflows/semantic-pr.yml
packages/eslint-config-typescript/package.json
packages/identity/package.json
packages/types/package.json
packages/typescript/package.json
packages/utils/package.json

Title says it all - changes all references to master to main

build: switch primary branch to main

---

package.json
packages/eslint-config-typescript/package.json
packages/identify/.eslintrc.json
packages/identify/.npmignore
packages/identify/LICENSE
packages/identify/README.md
packages/identify/jest.config.js
packages/identify/package.json
packages/identify/src/constants.ts
packages/identify/src/identify.ts
packages/identify/src/index.ts
packages/identify/tests/identify.spec.ts
packages/identify/tsconfig.build.json
packages/identify/tsconfig.esm.json
packages/identify/tsconfig.json
packages/identity/package.json
packages/node/package.json
packages/node/src/nodeClient.ts
packages/types/package.json
packages/types/src/base-event.ts
packages/types/src/baseEvent.ts
packages/types/src/event.ts
packages/types/src/identify.ts
packages/types/src/index.ts
packages/types/src/transport.ts
packages/typescript/package.json
packages/utils/package.json

#37 # Summary
The work needed to build a way to interface with the Identify API, similar to how the JS SDK currently does.
This is a WIP and we plan on adding:
Note: The tests will fail to build until Identify is added to the NPM registry, but until then I ran the tests locally to ensure they worked.
But wanted to start garnering feedback on design, use, etc.
Resolves Issue #13 

feat: Identify API

---

packages/node/src/nodeClient.ts

Allow not overriding the platform if this value was passed in.
Not doing the same for library since this is reserved for the SDK 

feat(event): allow passing in of platform

---

packages/types/src/baseEvent.ts

feat: Add more event types

---

packages/types/src/identify.ts

Changes the enum values to the ones correct for the http v2 API

fix(identify): fix wrong fields on post and pre-insert

---

packages/identify/src/constants.ts
packages/identify/src/identify.ts
packages/types/src/identify.ts
packages/utils/src/index.ts
packages/utils/src/validateProperties.ts
packages/utils/test/validateProperties.test.ts

feat(identify): make identify API accept deep object as value

---

packages/utils/src/validate.ts
packages/utils/test/validate.test.ts

feat(validate): Added event property type object validation.

---

packages/node/src/transports/http.ts
packages/node/test/http.test.ts
packages/types/src/response.ts
packages/types/src/status.ts
packages/utils/src/queue.ts
packages/utils/src/response.ts
packages/utils/src/status.ts

Simplify how timeouts are handled for event logging and solve a few issues with it
* Does your PR have a breaking change?: No

fix(timeouts): Amp 34805

---

packages/node/src/constants.ts
packages/node/src/transports/http.ts
packages/node/test/http.test.ts
packages/node/test/mocks/transport.ts
packages/types/src/options.ts
packages/types/src/transport.ts

Enables configurable timeout duration for event requests.

feat: Support Custom Request Timeout

---

.github/workflows/codeql-analysis.yml

This is a trial test for code ql analysis

test: create codeql-analysis.yml

---

packages/node/src/nodeClient.ts
packages/types/src/baseEvent.ts
packages/types/src/options.ts
packages/types/src/plan.ts

add observe tracking plan support, passed in options and send the information with every event

feat: add observe tracking plan information support

---

.github/workflows/publish-github-packages.yml

New workflow to publish packages to GitHub NPM registry.

chore: AMP-42717 Ability to publish github packages

---

.github/workflows/publish-github-packages.yml

Updated GH packages authorize step to allow admin to publish

chore: AMP-42717 Updated GH packages authorize step to allow admin to publish

---

.github/workflows/publish-github-packages.yml

Use prerelease version for GH packages publishing
* Does your PR have a breaking change?: No

chore: AMP-42717 Updated GH packages to use prerelease version

---

.github/workflows/publish-github-packages.yml

AMP-42717 Updated GH packages workflow to allow setting version
* Does your PR have a breaking change?: No

chore: AMP-42717 Updated GH packages workflow to allow setting version

---

.github/workflows/publish-github-packages.yml

Added missing $ to GH workflow
* Does your PR have a breaking change?: No

chore: AMP-42717 Added missing $ to GH workflow

---

.github/workflows/jira-issue-create.yml

update jira bot
* Does your PR have a breaking change?:  no

chore: update jira bot

---

.github/workflows/jira-issue-create.yml

chore: use the reusable flow for jira creation

---

packages/identify/package.json
packages/identity/package.json
packages/node/package.json
packages/utils/package.json

chore: upgrade tslib to v2.0.0

---

README.md

docs: legacy Announcement
